name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
  - cron: '00 01 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up rye
        uses: eifinger/setup-rye@v3
      - name: Sync dependencies using rye
        run: |
          rye config --set-bool behavior.use-uv=false
          rye pin ${{ matrix.python-version }}
          rye sync
      - name: Run tests with pytest
        run: |
          rye run pytest -vv -x
